### ISSUE TITLE
Script is missing that Find My is turned on

### ISSUE THREAD

**Issue by Cristal98** [bvanpeski/unActivationLock#13]
I ran the script on a device where I had Find My turned on for testing purposes, but it seems it's not picking this up. 
The response is empty and says that the activation lock is disabled. This device is on Sonoma 14.3.1.
Any idea why it would be return this as such?
Thank you.

<img width="437" alt="Screenshot 2024-02-22 at 1 29 34 PM" src="https://github.com/bvanpeski/unActivationLock/assets/99671162/e2359947-a0fb-40e1-8644-003137db0515">
<img width="396" alt="Screenshot 2024-02-22 at 1 30 39 PM" src="https://github.com/bvanpeski/unActivationLock/assets/99671162/01af4868-0a9d-4969-b1c7-7d708533c17e">

**Comment by bvanpeski** [comment]
It checks the Find My status of the machines by checking the value in `/Users/$currentUser/Library/Preferences/MobileMeAccounts.plist`.  Either there was a delay in Apple writing that value to the plist or something else is up... I tested the script on a 14.3.1 machine and am getting the correct output.
<img width="538" alt="image" src="https://github.com/bvanpeski/unActivationLock/assets/4316081/de63233e-060d-4ee4-bd24-722b444dde31">

Did it eventually correct itself, or is it still reporting that FindMy is not enabled even though it is?

**Comment by itsmeadamdamroma** [comment]
hi [bvanpeski], there is a guide to use the code for newbies ?

**Comment by bvanpeski** [comment]
> hi [bvanpeski], there is a guide to use the code for newbies ?

Deploy the [script](https://github.com/bvanpeski/unActivationLock/blob/main/unActivationLock.zsh) via your MDM and modify the User Input section of the script if you want to change any of the default parameters. If you need help deploying scripts via your MDM solution, you can reach out to their support teams. There's also a great community of admins over at the [MacAdmins Slack](https://macadmins.org) that are always happy to assist and answer questions as well.
