### ISSUE TITLE
Two Possible Issues for some situations

### ISSUE THREAD

**Issue by damacguy** [bvanpeski/unActivationLock#5]
I'm not confident enough in my coding ability to submit changes, but there are two situations you might want to account for...
1. Machines that aren't running 13.x - I added this to my version...
> SWtest=$(sw_vers | grep ProductVersion | awk '{print$2}' | cut -c 1-2)
> if [[ "$SWtest" -lt  "13" ]];then
>     SysPref="System Preferences"
> else
>     SysPref="System Settings"
> fi
...and then changed each instance of "System Settings" to "'"$SysPref"'"' to open the correct one.

2.  I actually did have one machine that came back with no users with a FindMy token associated. I didn't have time to troubleshoot, but the current logged in user WAS the one with their AppleID signed in and FindMy enabled. And wee have several machines with a generic login (i.e. "editor") and for some reason the fools enabled their AppleID. (facepalm).

So I'm working to add one dialog subroutine that'll alert the signed in user to see if they can disable Find My if 'no user' was reported, and another sub-routine to say what AppleID is being used and to warn the signed in user if they're that user to sign out of that AppleID account (or at least disable Find My).

**Comment by bvanpeski** [comment]
1. That `osascript -e 'tell application "System Settings"' -e 'activate' -e 'end tell'` line is just to account for a weird bug in Ventura, so I didn't include any logic to do the same on Monterey. I should probably add that in the comments on the next update so it's more clear.

2. It looks this issue CAN occur in some scenarios. I'll add some additional clarity for when that scenario crops up.

**Comment by bvanpeski** [comment]
Added some more clarity in https://github.com/bvanpeski/unActivationLock/pull/10.
