### ISSUE TITLE
Something is wonky... - can happen

### ISSUE THREAD

**Issue by delize** [bvanpeski/unActivationLock#8]
```shell
elif [[ $activationLock == "Enabled" && -z $FindMyUser ]]; then
      LOGGING "Activation lock status is $activationLock, and there are no users with a FindMy token associated. Something is wonky..."
      #I don't think this can happen, but leaving it here just in case.
```
[Source](https://github.com/bvanpeski/unActivationLock/blob/97a693b6e6aa87097852f6a56995050d23a73344/unActivationLock.zsh#L133-135)

Can confirm, this can happen. :) 

```
Script result: Activation Lock Status: Enabled | ADE-Enrolled: Yes
--- User-Based Activation Lock is: Enabled. Checking local users...
--- Checking Activation Lock status for the following users: first.last Jamfadmin...
Activation lock status is Enabled, and there are no users with a FindMy token associated. Something is wonky...
```
Username changed to `first.last`

I can confirm that the device does have Find My enabled, based on the output of: 
`fmmToken=$(/usr/sbin/nvram -x -p | /usr/bin/grep "fmm-mobileme-token-FMM")`

But according to the output of:
`/usr/libexec/PlistBuddy -c print "/Users/first.last/Library/Preferences/MobileMeAccounts.plist"`

```        Dict {
          apsEnv = production
          url = https://p52-fmip.icloud.com:443
          pairingURL = https://gateway.icloud.com/fmadminws
          authMechanism = token
          hostname = p52-fmip.icloud.com
          appHostname = p52-fmipmobile.icloud.com
          Name = FIND_MY_MAC
          Enabled = false
          ServiceID = com.apple.Dataclass.DeviceLocator
        }
```
This file does not exist for Jamfadmin.

Under System Settings > iCloud, Find My Mac is turned on.
![image](https://user-images.githubusercontent.com/4028612/222116747-9c4aef14-552a-417f-b2c5-cb3e752bc764.png)

**Comment by bvanpeski** [comment]
Hmm... So either the Find My status wasn't written properly to `MobileMeAccounts.plist` and/or the cached activation lock status is incorrect. If you're able to re-create at all, let me know!

**Comment by delize** [comment]
Got a response today that the employee's device randomly started prompting to him to disable Find My, so it magically started working without any change from my side (in terms of management).

**Comment by bvanpeski** [comment]
"Apple: It Just Works. Eventually"

**Comment by ps-spb** [comment]
Just to jump in on this, I have two machines with the same issue in case you want more help to debug this edge case.

**Comment by bvanpeski** [comment]
@ps-spb If you can reach out to me on MacAdmins Slack (brianvp) I'd love to get more details from you.

**Comment by bvanpeski** [comment]
Tried to address this with just some additional logging in https://github.com/bvanpeski/unActivationLock/pull/10.
